 
export function buildAnalysisPrompt(code, language, mode) {
  const base = `You are a cybersecurity expert analyzing ${language} code. The code to analyze is:

\`\`\`${language}
${code}
\`\`\`

`;

  const modeInstructions = {
    adversary: `ADVERSARY PERSONA - You are a red team penetration tester. Your mission is to find every exploitable vulnerability. Think like an attacker:
- Identify injection points, authentication bypasses, privilege escalation paths
- Explain exactly HOW each vulnerability would be exploited step by step
- Rate the exploitability and impact
- Show attack payloads or exploit code where applicable
- Map how vulnerabilities chain together (e.g., XSS leads to session hijack leads to admin access)
- Identify the application layer each vulnerability exists in (frontend, backend, database, network)
- Reference CWE identifiers and OWASP Top 10 categories`,

    defender: `BLUE TEAM DEFENDER PERSONA - You are a security engineer providing defensive analysis:
- Identify all security vulnerabilities with their severity
- For EACH finding, provide a specific, production-ready code patch
- Explain the defensive principle behind each fix
- Suggest architectural improvements for defense-in-depth
- Recommend security headers, CSP policies, input validation rules
- Identify the application layer and suggest layer-specific controls
- Reference CWE identifiers and OWASP Top 10 categories
- Prioritize fixes by risk reduction impact`,

    audit: `AI CODE AUDITOR PERSONA - You specialize in evaluating code that was generated by AI assistants (GitHub Copilot, ChatGPT, etc.). Focus on:
- Patterns commonly produced by AI that are insecure (e.g., missing input validation, SQL string concatenation, hardcoded secrets, improper error handling)
- Data type validation issues that AI assistants typically skip
- Exception handling that's too broad or missing entirely
- Insecure defaults that AI tends to generate
- Security anti-patterns statistically propagated from training data
- Missing security controls that a human security-aware developer would include
- Mark each finding with ai_source_concern: true if it's a pattern typical of AI-generated code
- Reference CWE identifiers and OWASP Top 10 categories`,
  };

  const responseSchema = `
Respond with a JSON object containing a "findings" array. Each finding must have:
- title: string (concise vulnerability name)
- description: string (detailed explanation)
- severity: "critical" | "high" | "medium" | "low" | "info"
- cwe_id: string (e.g., "CWE-79")
- owasp_category: one of "A01_Broken_Access_Control", "A02_Cryptographic_Failures", "A03_Injection", "A04_Insecure_Design", "A05_Security_Misconfiguration", "A06_Vulnerable_Components", "A07_Auth_Failures", "A08_Data_Integrity_Failures", "A09_Logging_Failures", "A10_SSRF"
- code_line: number (approximate line number)
- code_context: string (the vulnerable code snippet)
- attack_vector: string (how to exploit this - be specific)
- remediation: string (specific fix with code example if possible)
- layer: "frontend" | "backend" | "database" | "network" | "infrastructure"
- chain_position: number (0 = entry point, higher = deeper in chain)
- leads_to: string[] (titles of other findings this could chain to)
- ai_source_concern: boolean (true if typical of AI-generated code)
- detected_by: "${mode === 'adversary' ? 'ai_adversary' : mode === 'defender' ? 'ai_defender' : 'ai_auditor'}"`;

  return {
    prompt: base + modeInstructions[mode] + '\n\n' + responseSchema,
    schema: {
      type: 'object',
      properties: {
        findings: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              title: { type: 'string' },
              description: { type: 'string' },
              severity: { type: 'string' },
              cwe_id: { type: 'string' },
              owasp_category: { type: 'string' },
              code_line: { type: 'number' },
              code_context: { type: 'string' },
              attack_vector: { type: 'string' },
              remediation: { type: 'string' },
              layer: { type: 'string' },
              chain_position: { type: 'number' },
              leads_to: { type: 'array', items: { type: 'string' } },
              ai_source_concern: { type: 'boolean' },
              detected_by: { type: 'string' },
            }
          }
        }
      }
    }
  };
}

export function buildChainAnalysisPrompt(vulnerabilities) {
  const vulnSummary = vulnerabilities.map(v => 
    `- ${v.title} (${v.severity}, ${v.layer}, ${v.cwe_id}): ${v.description}`
  ).join('\n');

  return {
    prompt: `You are a cybersecurity attack chain analysis expert. Given these vulnerabilities found in an application:

${vulnSummary}

Analyze how these vulnerabilities can be chained together into attack paths. Think about:
1. Which vulnerability serves as the initial entry point?
2. How can an attacker pivot from one vulnerability to the next?
3. What is the maximum damage achievable through chaining?
4. Where do multiple attack paths converge (critical intersection points)?
5. What are the most effective defensive measures to break the chains?

Provide your analysis as a structured graph with nodes (vulnerabilities) and edges (attack flow), plus chain-breaker recommendations.`,
    schema: {
      type: 'object',
      properties: {
        nodes: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              id: { type: 'string' },
              title: { type: 'string' },
              severity: { type: 'string' },
              layer: { type: 'string' },
              is_entry_point: { type: 'boolean' },
              is_critical_intersection: { type: 'boolean' },
            }
          }
        },
        edges: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              from: { type: 'string' },
              to: { type: 'string' },
              method: { type: 'string' },
              difficulty: { type: 'string' },
            }
          }
        },
        attack_paths: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              name: { type: 'string' },
              steps: { type: 'array', items: { type: 'string' } },
              impact: { type: 'string' },
              likelihood: { type: 'string' },
            }
          }
        },
        critical_intersections: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              node_id: { type: 'string' },
              title: { type: 'string' },
              converging_paths: { type: 'number' },
              reason: { type: 'string' },
            }
          }
        },
        chain_breaker_recommendations: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              title: { type: 'string' },
              description: { type: 'string' },
              type: { type: 'string' },
              breaks_chains: { type: 'array', items: { type: 'string' } },
              effort: { type: 'string' },
              impact: { type: 'string' },
            }
          }
        },
        overall_risk_score: { type: 'number' },
        summary: { type: 'string' },
      }
    }
  };
}